FROM node:15-alpine
# CMD ["npm","run","build"]

# FROM node:12.8-alpine
# WORKDIR /usr/src/app
# COPY package.json package-lock.json ./
# RUN npm install
# COPY . .
# RUN npm run build

# FROM nginx:1.19-alpine
# COPY --from=build-stage /usr/src/app/dist /var/www/app
# COPY ../../.docker/nginx/conf.d/app.conf /etc/nginx/conf.d/app.conf
